/* EXRECÍCIO 1 - DADOS LIVRARIA*/

/* O CLIENTE SOLICITOU UMA TABELA PARA ARMAZENAR OS LIVROS QUES SÃO COMERCIALIZADOS PELA
EMPRESA. A SOLICITAÇÃO É SOMENTE PARA LIVROS E NÃO HÁ A NECESSIDADE DE REALIZAR A BUSCA EM
OUTRAS TABELAS. HOJE HÁ UM FUNCIONÁRIO DE VENDAS QUE TEM UMA TABELA (EXCEL) PARA GUARDAR 
ESSES REGISTROS, MAS AS BUSCAS ESTÃO FICANDO COMPLEXAS. DECIDIU-SE ENTÃO CRIAR UM BANCO DE DADOS
SEPARADO PARA ESSE FUNCIONÁRIO

APÓS A CRIAÇÃO DA TABELA, DEVE-SE ENTREGAR ALGUMAS QUERIES PRONTAS PARA QUE SEJAM ENVIADAS PARA
O PROGRAMADOR. AS QUERIES SÃO AS SEGUINTES:

1 - TRAZER TODOS OS DADOS;
2 - TRAZER O NOME DO LIVRO E O NOME DA EDITORA;
3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO;
4 - TRAZER O NOME DO LIVRO E O NÚMERO DE  PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO
FEMININO;
5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO;
6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO
OU RIO DE JANEIRO.

*/

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE LIVRARIA;

/* ACESSANDO O BANCO DE DADOS */

USE LIVRARIA;

/* CRIANDO A ENTIDADE PARA INSERÇÃO DOS ATRIBUTOS */

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(6),
	EDITORA VARCHAR(30),
	VALOR FLOAT(5),
	UF CHAR(2),
	ANO INT(4)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* ANALISANDO A ESTRUTURA DE UMA TABELA */

DESC LIVROS;

/* INSERINDO OS ATRIBUTOS NA ENTIDADE LIVROS */

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'SQL PARA LEIGOS', 'JOAO GOMES', 'M', 450, 'ADDISON', 98, 'SP', 2018 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'HABITOS SAUDAVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA', 150.98, 'RJ', 2019 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'ESTACIO QUERIDO', 'GERALDO FRANSCISCO', 'M', 310, 'INSIGNIA', 100, 'ES', 2015 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', 2011 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'COPAS INESQUECÍVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018 );

INSERT INTO LIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES(
'O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017 );

/* PROJETANDO OS ATRIBUTOS NA ENTIDADE LIVROS */

/* 1 - TRAZER TODOS OS DADOS; */
SELECT LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO FROM LIVROS;

/* 2 - TRAZER O NOME DO LIVRO E O NOME DA EDITORA; */
SELECT LIVRO, EDITORA FROM LIVROS;

/* 3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO; */
SELECT LIVRO, UF FROM LIVROS
WHERE SEXO = 'M';

/* 4 - TRAZER O NOME DO LIVRO E O NÚMERO DE  PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO
FEMININO; */
SELECT LIVRO, PAGINAS FROM LIVROS
WHERE SEXO = 'F';

/* 5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO; */
SELECT EDITORA FROM LIVROS
WHERE UF = 'SP';

/* 6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS EM SÃO PAULO
OU RIO DE JANEIRO. */
SELECT AUTOR, SEXO, UF 
FROM LIVROS
WHERE SEXO = 'M'
AND (UF = 'RJ' OR UF ='SP');

/* 7 - TRAZER OS DADOS DOS LIVROS COM VALORES ENTRE 100 E 200 REAIS */
SELECT AUTOR, SEXO, UF, VALOR 
FROM LIVROS
WHERE VALOR > 100 AND VALOR< 200;